@baseUrl = http://localhost:8081
### login
POST {{baseUrl}}/api/auth/login

{
    "email": "manager@dev.com",
    "password": "admin1234"
}

### register
POST {{baseUrl}}/api/auth/register

{
    "email": "manager@gmail.com",
    "password": "manager"
}
